[38;2;248;248;242mname: Deploy to GitHub Pages[0m
[38;2;248;248;242mon:[0m
[38;2;248;248;242m  push:[0m
[38;2;248;248;242m    branches: [gh-pages, main][0m
[38;2;248;248;242mpermissions:[0m
[38;2;248;248;242m  contents: read[0m
[38;2;248;248;242m  pages: write[0m
[38;2;248;248;242m  id-token: write[0m
[38;2;248;248;242mconcurrency:[0m
[38;2;248;248;242m  group: "pages"[0m
[38;2;248;248;242m  cancel-in-progress: false[0m
[38;2;248;248;242mjobs:[0m
[38;2;248;248;242m  deploy:[0m
[38;2;248;248;242m    environment:[0m
[38;2;248;248;242m      name: github-pages[0m
[38;2;248;248;242m      url: ${{ steps.deployment.outputs.page_url }}[0m
[38;2;248;248;242m    runs-on: ubuntu-latest[0m
[38;2;248;248;242m    steps:[0m
[38;2;248;248;242m      - uses: actions/checkout@v4[0m
[38;2;248;248;242m      - uses: actions/configure-pages@v4[0m
[38;2;248;248;242m      - uses: actions/upload-pages-artifact@v3[0m
[38;2;248;248;242m        with:[0m
[38;2;248;248;242m          path: '.'[0m
[38;2;248;248;242m      - name: Deploy to GitHub Pages[0m
[38;2;248;248;242m        id: deployment[0m
[38;2;248;248;242m        uses: actions/deploy-pages@v4[0m
